package com.mycompany.oumaima;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Consultation_info_patient extends javax.swing.JFrame {

    /**
     * Creates new form Consultation_info_patient
     */
    public Consultation_info_patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblSaisirIDPateint = new javax.swing.JLabel();
        TxtIDPatient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnidPatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LblSaisirIDPateint.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        LblSaisirIDPateint.setForeground(new java.awt.Color(0, 102, 102));
        LblSaisirIDPateint.setText("Saisir l'identifiant du patient ");
        getContentPane().add(LblSaisirIDPateint);
        LblSaisirIDPateint.setBounds(59, 29, 379, 48);

        TxtIDPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDPatientActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIDPatient);
        TxtIDPatient.setBounds(185, 88, 194, 28);

        jLabel1.setText("id Patient");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 90, 81, 20);

        BtnidPatient.setBackground(new java.awt.Color(0, 102, 102));
        BtnidPatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnidPatient.setForeground(new java.awt.Color(0, 153, 153));
        BtnidPatient.setText("S'identifier");
        getContentPane().add(BtnidPatient);
        BtnidPatient.setBounds(360, 150, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIDPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultation_info_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultation_info_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultation_info_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultation_info_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultation_info_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnidPatient;
    private javax.swing.JLabel LblSaisirIDPateint;
    private javax.swing.JTextField TxtIDPatient;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
