package com.mycompany.oumaima;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Lenovo
 */
public class Gestion_mesures extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_mesures
     */
    public Gestion_mesures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTaille = new javax.swing.JLabel();
        LblPoids = new javax.swing.JLabel();
        LblPression = new javax.swing.JLabel();
        LblTension = new javax.swing.JLabel();
        LblTepertaure = new javax.swing.JLabel();
        LblTaucCellule = new javax.swing.JLabel();
        TxtPression = new javax.swing.JTextField();
        TxtTension = new javax.swing.JTextField();
        TxtPoids = new javax.swing.JTextField();
        TxtTaille = new javax.swing.JTextField();
        TxtTauxCellule = new javax.swing.JTextField();
        TxtTempr = new javax.swing.JTextField();
        LblTension1 = new javax.swing.JLabel();
        LblTension2 = new javax.swing.JLabel();
        TxtGsc = new javax.swing.JTextField();
        TxtPH = new javax.swing.JTextField();
        BtnValider = new javax.swing.JButton();
        LblChamps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        LblTaille.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTaille.setForeground(new java.awt.Color(0, 102, 102));
        LblTaille.setText("Taille");
        LblTaille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTaille);
        LblTaille.setBounds(21, 172, 90, 33);

        LblPoids.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPoids.setForeground(new java.awt.Color(0, 102, 102));
        LblPoids.setText("Poids");
        LblPoids.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblPoids);
        LblPoids.setBounds(21, 101, 90, 33);

        LblPression.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPression.setForeground(new java.awt.Color(0, 102, 102));
        LblPression.setText("Pression");
        LblPression.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblPression);
        LblPression.setBounds(380, 100, 90, 33);

        LblTension.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTension.setForeground(new java.awt.Color(0, 102, 102));
        LblTension.setText("Tension");
        LblTension.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTension);
        LblTension.setBounds(380, 230, 90, 33);

        LblTepertaure.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTepertaure.setForeground(new java.awt.Color(0, 102, 102));
        LblTepertaure.setText("Température");
        LblTepertaure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTepertaure);
        LblTepertaure.setBounds(20, 240, 90, 33);

        LblTaucCellule.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTaucCellule.setForeground(new java.awt.Color(0, 102, 102));
        LblTaucCellule.setText("TauxCellule");
        LblTaucCellule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTaucCellule);
        LblTaucCellule.setBounds(380, 170, 90, 33);

        TxtPression.setText("pression");
        getContentPane().add(TxtPression);
        TxtPression.setBounds(493, 173, 112, 33);

        TxtTension.setText("tension");
        getContentPane().add(TxtTension);
        TxtTension.setBounds(490, 230, 112, 33);

        TxtPoids.setText("Poids");
        TxtPoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPoidsActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPoids);
        TxtPoids.setBounds(129, 102, 112, 33);

        TxtTaille.setText("taille");
        getContentPane().add(TxtTaille);
        TxtTaille.setBounds(129, 173, 112, 33);

        TxtTauxCellule.setText("tauxcellule");
        getContentPane().add(TxtTauxCellule);
        TxtTauxCellule.setBounds(493, 102, 112, 33);

        TxtTempr.setText("Température");
        getContentPane().add(TxtTempr);
        TxtTempr.setBounds(130, 240, 112, 33);

        LblTension1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTension1.setForeground(new java.awt.Color(0, 102, 102));
        LblTension1.setText("Ph");
        LblTension1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTension1);
        LblTension1.setBounds(20, 300, 90, 33);

        LblTension2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTension2.setForeground(new java.awt.Color(0, 102, 102));
        LblTension2.setText("Gsc");
        LblTension2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LblTension2);
        LblTension2.setBounds(380, 290, 90, 33);

        TxtGsc.setText("gsc");
        getContentPane().add(TxtGsc);
        TxtGsc.setBounds(490, 290, 112, 33);

        TxtPH.setText("ph");
        getContentPane().add(TxtPH);
        TxtPH.setBounds(129, 297, 112, 33);

        BtnValider.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BtnValider.setForeground(new java.awt.Color(0, 153, 153));
        BtnValider.setText("Valider");
        getContentPane().add(BtnValider);
        BtnValider.setBounds(213, 376, 161, 33);

        LblChamps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblChamps.setText("Veuillez saisir les champs suivants ");
        getContentPane().add(LblChamps);
        LblChamps.setBounds(150, 30, 330, 40);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPoidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_mesures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnValider;
    private javax.swing.JLabel LblChamps;
    private javax.swing.JLabel LblPoids;
    private javax.swing.JLabel LblPression;
    private javax.swing.JLabel LblTaille;
    private javax.swing.JLabel LblTaucCellule;
    private javax.swing.JLabel LblTension;
    private javax.swing.JLabel LblTension1;
    private javax.swing.JLabel LblTension2;
    private javax.swing.JLabel LblTepertaure;
    private javax.swing.JTextField TxtGsc;
    private javax.swing.JTextField TxtPH;
    private javax.swing.JTextField TxtPoids;
    private javax.swing.JTextField TxtPression;
    private javax.swing.JTextField TxtTaille;
    private javax.swing.JTextField TxtTauxCellule;
    private javax.swing.JTextField TxtTempr;
    private javax.swing.JTextField TxtTension;
    // End of variables declaration//GEN-END:variables
}
