package com.mycompany.oumaima;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Interface_Mesures extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Mesures
     */
    public Interface_Mesures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblMesures = new javax.swing.JLabel();
        BtnID_mesure_patient = new javax.swing.JLabel();
        TxtID_mesure = new javax.swing.JTextField();
        BtnIdPatient_mesure = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LblMesures.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        LblMesures.setText("Gestion des Mesures");
        getContentPane().add(LblMesures);
        LblMesures.setBounds(30, 20, 332, 43);

        BtnID_mesure_patient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnID_mesure_patient.setForeground(new java.awt.Color(0, 102, 204));
        BtnID_mesure_patient.setText("Veuillez Entrer l'id du patient");
        getContentPane().add(BtnID_mesure_patient);
        BtnID_mesure_patient.setBounds(40, 90, 231, 52);

        TxtID_mesure.setText("ID du patient");
        TxtID_mesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtID_mesureActionPerformed(evt);
            }
        });
        getContentPane().add(TxtID_mesure);
        TxtID_mesure.setBounds(270, 100, 223, 31);

        BtnIdPatient_mesure.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        BtnIdPatient_mesure.setText("S'identifier");
        BtnIdPatient_mesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIdPatient_mesureActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIdPatient_mesure);
        BtnIdPatient_mesure.setBounds(460, 160, 173, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtID_mesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtID_mesureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtID_mesureActionPerformed

    private void BtnIdPatient_mesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIdPatient_mesureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIdPatient_mesureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Mesures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Mesures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnID_mesure_patient;
    private javax.swing.JButton BtnIdPatient_mesure;
    private javax.swing.JLabel LblMesures;
    private javax.swing.JTextField TxtID_mesure;
    // End of variables declaration//GEN-END:variables
}
