/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

/**
 *
 * @author hp
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcomboCategorie = new javax.swing.JComboBox<>();
        jpassword = new javax.swing.JPasswordField();
        jlblUsername = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jbtnValider = new javax.swing.JButton();
        jbtnAnnuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        getContentPane().setLayout(null);

        jcomboCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Secretaire", "Medecin", "Infirmière" }));
        jcomboCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboCategorieActionPerformed(evt);
            }
        });
        getContentPane().add(jcomboCategorie);
        jcomboCategorie.setBounds(220, 160, 120, 20);
        getContentPane().add(jpassword);
        jpassword.setBounds(220, 120, 120, 20);

        jlblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblUsername.setText("Login");
        getContentPane().add(jlblUsername);
        jlblUsername.setBounds(80, 80, 50, 17);

        jlblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblPassword.setText("Mot de passe");
        getContentPane().add(jlblPassword);
        jlblPassword.setBounds(80, 120, 100, 15);
        getContentPane().add(jtfUsername);
        jtfUsername.setBounds(220, 80, 120, 20);

        jbtnValider.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jbtnValider.setText("Entrer");
        jbtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnValider);
        jbtnValider.setBounds(60, 220, 80, 23);

        jbtnAnnuler.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jbtnAnnuler.setText("Annuler");
        jbtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAnnuler);
        jbtnAnnuler.setBounds(170, 220, 90, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Categorie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 170, 70, 15);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Clinique Ashila");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 190, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Bienvenue");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(317, 33, 90, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/Images/Accueil.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 440, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnValiderActionPerformed

    private void jbtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAnnulerActionPerformed

    private void jcomboCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboCategorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnAnnuler;
    private javax.swing.JButton jbtnValider;
    private javax.swing.JComboBox<String> jcomboCategorie;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblUsername;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
