/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class DossierMedical extends javax.swing.JFrame {

    /**
     * Creates new form DossierMedical
     */
    public DossierMedical() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNumDossier = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblNom = new javax.swing.JLabel();
        jtfNom = new javax.swing.JTextField();
        jlblPrenom = new javax.swing.JLabel();
        jlblAge = new javax.swing.JLabel();
        jlblSexe = new javax.swing.JLabel();
        jlblDateVisite = new javax.swing.JLabel();
        jlblCIN = new javax.swing.JLabel();
        jlblTel = new javax.swing.JLabel();
        jlblAdresse = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfAge = new javax.swing.JTextField();
        jtfDateVisite = new javax.swing.JTextField();
        jtfTel = new javax.swing.JTextField();
        jtfPrenom = new javax.swing.JTextField();
        jtfSexe = new javax.swing.JTextField();
        jtfCIN = new javax.swing.JTextField();
        jtfAdresse = new javax.swing.JTextField();
        jpConsultation = new javax.swing.JPanel();
        jlblNumConsultation = new javax.swing.JLabel();
        jlblTemperature = new javax.swing.JLabel();
        jlblPoids = new javax.swing.JLabel();
        jlblTension = new javax.swing.JLabel();
        jlblTaille = new javax.swing.JLabel();
        jlblMotifs = new javax.swing.JLabel();
        jlblSignes = new javax.swing.JLabel();
        jlblAntecedents = new javax.swing.JLabel();
        jlblExamen = new javax.swing.JLabel();
        jlblDiagnostique = new javax.swing.JLabel();
        jlblOrdonnance = new javax.swing.JLabel();
        jtfTemperature = new javax.swing.JTextField();
        jtfPoids = new javax.swing.JTextField();
        jtfTension = new javax.swing.JTextField();
        jtfTaille = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMotifs = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaSignes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaAntecedents = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaExamen = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaDiagnostique = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtaOrdonnance = new javax.swing.JTextArea();
        jtfNumConsultation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlblNumConsultation1 = new javax.swing.JLabel();
        jtfDateConsultation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnOK = new javax.swing.JButton();

        jButton1.setText("OK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("N° Dossier");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblNom.setText("Nom");

        jlblPrenom.setText("Prenom");

        jlblAge.setText("Age");

        jlblSexe.setText("Sexe");

        jlblDateVisite.setText("Date de Visite");

        jlblCIN.setText("CIN");

        jlblTel.setText("Téléphone");

        jlblAdresse.setText("Adresse");

        jLabel2.setText("Coordonnées du Patient");

        jtfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDateVisite)
                            .addComponent(jlblNom)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlblAge))
                            .addComponent(jlblTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNom, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(jtfAge)
                                .addComponent(jtfDateVisite))
                            .addComponent(jtfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPrenom)
                            .addComponent(jlblSexe)
                            .addComponent(jlblCIN)
                            .addComponent(jlblAdresse)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jtfSexe)
                        .addComponent(jtfCIN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNom)
                    .addComponent(jlblPrenom)
                    .addComponent(jtfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblCIN))
                            .addComponent(jtfCIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblSexe)
                            .addComponent(jtfSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDateVisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblAge)
                        .addGap(14, 14, 14)
                        .addComponent(jlblDateVisite)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblAdresse)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblTel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpConsultation.setBackground(new java.awt.Color(255, 255, 255));
        jpConsultation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblNumConsultation.setText("Num Consultation");

        jlblTemperature.setText("Temperature");

        jlblPoids.setText("Poids(Kg)");

        jlblTension.setText("Tension");

        jlblTaille.setText("Taille");

        jlblMotifs.setText("Motifs de Consultation");

        jlblSignes.setText("Signes généraux");

        jlblAntecedents.setText("Antécédents");

        jlblExamen.setText("Examen");

        jlblDiagnostique.setText("Diagnostique");

        jlblOrdonnance.setText("Ordonnance");

        jtfTension.setFocusable(false);

        jtaMotifs.setColumns(20);
        jtaMotifs.setRows(5);
        jScrollPane1.setViewportView(jtaMotifs);

        jtaSignes.setColumns(20);
        jtaSignes.setRows(5);
        jScrollPane2.setViewportView(jtaSignes);

        jtaAntecedents.setColumns(20);
        jtaAntecedents.setRows(5);
        jScrollPane3.setViewportView(jtaAntecedents);

        jtaExamen.setColumns(20);
        jtaExamen.setRows(5);
        jScrollPane4.setViewportView(jtaExamen);

        jtaDiagnostique.setColumns(20);
        jtaDiagnostique.setRows(5);
        jScrollPane5.setViewportView(jtaDiagnostique);

        jtaOrdonnance.setColumns(20);
        jtaOrdonnance.setRows(5);
        jScrollPane6.setViewportView(jtaOrdonnance);

        jLabel3.setText("Consultation");

        jlblNumConsultation1.setText("Date de Consultation");

        javax.swing.GroupLayout jpConsultationLayout = new javax.swing.GroupLayout(jpConsultation);
        jpConsultation.setLayout(jpConsultationLayout);
        jpConsultationLayout.setHorizontalGroup(
            jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultationLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpConsultationLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultationLayout.createSequentialGroup()
                        .addComponent(jlblExamen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpConsultationLayout.createSequentialGroup()
                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpConsultationLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblMotifs)
                                    .addGroup(jpConsultationLayout.createSequentialGroup()
                                        .addComponent(jlblTemperature)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlblPoids)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jlblTension)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfTension, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpConsultationLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlblNumConsultation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNumConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jlblNumConsultation1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDateConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpConsultationLayout.createSequentialGroup()
                                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpConsultationLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jlblDiagnostique)
                                        .addGap(111, 111, 111)
                                        .addComponent(jlblOrdonnance))
                                    .addGroup(jpConsultationLayout.createSequentialGroup()
                                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblSignes)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jScrollPane6)
                                            .addGroup(jpConsultationLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jlblTaille)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jlblAntecedents))))))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jpConsultationLayout.setVerticalGroup(
            jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultationLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDateConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNumConsultation1)
                    .addComponent(jlblNumConsultation))
                .addGap(24, 24, 24)
                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPoids)
                    .addComponent(jtfPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTemperature)
                    .addComponent(jlblTension)
                    .addComponent(jtfTension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTaille)
                    .addComponent(jtfTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMotifs)
                    .addComponent(jlblSignes)
                    .addComponent(jlblAntecedents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsultationLayout.createSequentialGroup()
                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDiagnostique)
                            .addComponent(jlblOrdonnance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpConsultationLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblExamen)
                        .addGap(156, 156, 156))))
        );

        jLabel4.setText("Fiche médical");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 225, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfNumDossier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpConsultation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumDossier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE))
        );

        jbtnOK.setText("OK");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnOK)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnOK)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelActionPerformed

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        // TODO add your handling code here:
                PrinterJob job = PrinterJob.getPrinterJob();
job.setPrintable(new Printable() {
 
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
         
        int marge=30;
        int x = (int)pageFormat.getImageableX();
        int y = (int)pageFormat.getImageableY();
                 
        graphics.setFont(new Font("Times new roman", Font.BOLD, 14));
        graphics.setColor(Color.BLACK);
        //graphics.drawString("ACTE DEMANDER\n", x + marge, y + marge);
        jPanel1.printAll(graphics);
//panel.print(graphics);;           
 
        return PAGE_EXISTS;
            }
 
        });
boolean doPrint = job.printDialog();
if(doPrint) {
    try {
         
        job.print();
    }
    catch (PrinterException e1) {
            JOptionPane.showMessageDialog(null, e1);
    }
}
    }//GEN-LAST:event_jbtnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DossierMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DossierMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DossierMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DossierMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DossierMedical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JLabel jlblAdresse;
    private javax.swing.JLabel jlblAge;
    private javax.swing.JLabel jlblAntecedents;
    private javax.swing.JLabel jlblCIN;
    private javax.swing.JLabel jlblDateVisite;
    private javax.swing.JLabel jlblDiagnostique;
    private javax.swing.JLabel jlblExamen;
    private javax.swing.JLabel jlblMotifs;
    private javax.swing.JLabel jlblNom;
    private javax.swing.JLabel jlblNumConsultation;
    private javax.swing.JLabel jlblNumConsultation1;
    private javax.swing.JLabel jlblOrdonnance;
    private javax.swing.JLabel jlblPoids;
    private javax.swing.JLabel jlblPrenom;
    private javax.swing.JLabel jlblSexe;
    private javax.swing.JLabel jlblSignes;
    private javax.swing.JLabel jlblTaille;
    private javax.swing.JLabel jlblTel;
    private javax.swing.JLabel jlblTemperature;
    private javax.swing.JLabel jlblTension;
    private javax.swing.JPanel jpConsultation;
    private javax.swing.JTextArea jtaAntecedents;
    private javax.swing.JTextArea jtaDiagnostique;
    private javax.swing.JTextArea jtaExamen;
    private javax.swing.JTextArea jtaMotifs;
    private javax.swing.JTextArea jtaOrdonnance;
    private javax.swing.JTextArea jtaSignes;
    private javax.swing.JTextField jtfAdresse;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfCIN;
    private javax.swing.JTextField jtfDateConsultation;
    private javax.swing.JTextField jtfDateVisite;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfNumConsultation;
    private javax.swing.JTextField jtfNumDossier;
    private javax.swing.JTextField jtfPoids;
    private javax.swing.JTextField jtfPrenom;
    private javax.swing.JTextField jtfSexe;
    private javax.swing.JTextField jtfTaille;
    private javax.swing.JTextField jtfTel;
    private javax.swing.JTextField jtfTemperature;
    private javax.swing.JTextField jtfTension;
    // End of variables declaration//GEN-END:variables

    void setNumDossier(String text) {
        jtfNumDossier.setText(text); //To change body of generated methods, choose Tools | Templates.
    }

    void setNom(String string) {
        jtfNom.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setPrenom(String string) {
        jtfPrenom.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setAge(String string) {
        jtfAge.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setSexe(String string) {
        jtfSexe.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setDateVisite(String string) {
        jtfDateVisite.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setTel(String string) {
        jtfTel.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setCIN(String string) {
        jtfCIN.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setAdresse(String string) {
        jtfAdresse.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setNumConsultation(String string) {
        jtfNumConsultation.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setdateConsultation(String string) {
        jtfDateConsultation.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setTemperature(String string) {
        jtfTemperature.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setPoids(String string) {
        jtfPoids.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setTension(String string) {
        jtfTension.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setTaille(String string) {
        jtfTaille.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setMotifs(String string) {
        jtaMotifs.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setSignes(String string) {
        jtaSignes.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setAntecedents(String string) {
        jtaAntecedents.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setExamen(String string) {
        jtaExamen.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setDiagnostique(String string) {
        jtaDiagnostique.setText(string); //To change body of generated methods, choose Tools | Templates.
    }

    void setOrdonnance(String string) {
        jtaOrdonnance.setText(string); //To change body of generated methods, choose Tools | Templates.
    }
}
