/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class GestionDePatients extends javax.swing.JFrame {

    /**
     * Creates new form GestionDePatients
     */
    DefaultTableModel model = new DefaultTableModel();
    public GestionDePatients() {
        initComponents();
        model.addColumn("idP");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("age");
        model.addColumn("sexe");
        model.addColumn("date");
        model.addColumn("CIN");
        model.addColumn("telephone");
        model.addColumn("adresse");
        
        afficher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void deplace(int i){
        try{
            jtfId.setText(model.getValueAt(i, 0).toString());
            jtfNom.setText(model.getValueAt(i, 1).toString());
            jtfPrenom.setText(model.getValueAt(i, 2).toString());
            jtfAge.setText(model.getValueAt(i, 3).toString());
            if(model.getValueAt(i, 4).toString().equals("M")){
                jrbtnMasculin.setSelected(true);
            }
            else
                jrbtnFeminin.setSelected(true);
            jtfDate.setText(model.getValueAt(i, 5).toString());
            jtfTelephone.setText(model.getValueAt(i, 7).toString());
            jtfCIN.setText(model.getValueAt(i, 6).toString());
            jtfAdresse.setText(model.getValueAt(i, 8).toString());
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement");
        }
    }
    
    private void afficher(){
    try {
        model.setRowCount(0);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM patient;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String id = rs.getString("idP");
                String nom = rs.getString("nom");
                String prenom=rs.getString("prenom");
                String age=rs.getString("age");
                String sexe=rs.getString("sexe");
                String date=rs.getString("dateAdmission");
                String CIN=rs.getString("CIN");
                String telephone=rs.getString("telephone");
                String adresse=rs.getString("adresse");

                model.addRow (new Object[] {id,nom,prenom, age, sexe, date, CIN, telephone, adresse});
            }
            jtabPatient.setModel(model);

    }
    catch (SQLException e)
        {
            
        }

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSexe = new javax.swing.ButtonGroup();
        jbtnImprimer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlblNom = new javax.swing.JLabel();
        jlblPrenom = new javax.swing.JLabel();
        jlblSexe = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfTelephone = new javax.swing.JTextField();
        jtfCIN = new javax.swing.JTextField();
        jtfAdresse = new javax.swing.JTextField();
        jtfAge = new javax.swing.JTextField();
        jtfNom = new javax.swing.JTextField();
        jtfPrenom = new javax.swing.JTextField();
        jtfDate = new javax.swing.JTextField();
        jbtAjouter = new javax.swing.JButton();
        jbtnModifier = new javax.swing.JButton();
        jbtnSupprimer = new javax.swing.JButton();
        jbtnActualiser = new javax.swing.JButton();
        jbtnRechercher = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabPatient = new javax.swing.JTable();
        jlblId = new javax.swing.JLabel();
        jrbtnMasculin = new javax.swing.JRadioButton();
        jrbtnFeminin = new javax.swing.JRadioButton();
        toolBar = new javax.swing.JToolBar();
        tbtnRDV = new javax.swing.JButton();
        tbtnPatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des Patients");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnImprimer.setText("Imprimer Dossier médical");
        jbtnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimerActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Gestion des Patients");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jlblNom.setText("Nom");
        getContentPane().add(jlblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jlblPrenom.setText("Prenom");
        getContentPane().add(jlblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jlblSexe.setText("Sexe");
        getContentPane().add(jlblSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jlblDate.setText("Date");
        getContentPane().add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel7.setText("Telephone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel8.setText("CIN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel9.setText("Adresse");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        jLabel10.setText("Age");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jtfTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelephoneActionPerformed(evt);
            }
        });
        getContentPane().add(jtfTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 120, -1));
        getContentPane().add(jtfCIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 120, -1));
        getContentPane().add(jtfAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 210, -1));
        getContentPane().add(jtfAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, -1));

        jtfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomActionPerformed(evt);
            }
        });
        getContentPane().add(jtfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, -1));
        getContentPane().add(jtfPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, -1));

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");//format
        String s = sdf.format(new Date());
        jtfDate.setText(s);
        jtfDate.setEditable(false);
        jtfDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDateActionPerformed(evt);
            }
        });
        getContentPane().add(jtfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));

        jbtAjouter.setBackground(new java.awt.Color(102, 255, 255));
        jbtAjouter.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/ajoutP.png"))); // NOI18N
        jbtAjouter.setText("Ajouter");
        jbtAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 130, -1));

        jbtnModifier.setBackground(new java.awt.Color(102, 255, 255));
        jbtnModifier.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/modier.jpg"))); // NOI18N
        jbtnModifier.setText("Modifier");
        jbtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 130, 40));

        jbtnSupprimer.setBackground(new java.awt.Color(102, 255, 255));
        jbtnSupprimer.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/supprimer.png"))); // NOI18N
        jbtnSupprimer.setText("Supprimer");
        jbtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 130, -1));

        jbtnActualiser.setBackground(new java.awt.Color(102, 255, 255));
        jbtnActualiser.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/actualiser.png"))); // NOI18N
        jbtnActualiser.setText("Actualiser");
        jbtnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualiserActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 130, 40));

        jbtnRechercher.setBackground(new java.awt.Color(102, 255, 255));
        jbtnRechercher.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/rechercher.png"))); // NOI18N
        jbtnRechercher.setText("Rechercher");
        jbtnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 140, 40));

        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });
        getContentPane().add(jtfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 40));

        jtabPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Patient", "Nom", "Prenom", "Age", "Sexe", "Date", "Telephone", "CIN", "Adresse"
            }
        ));
        jtabPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabPatient);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 830, 230));

        jlblId.setText("Id");
        getContentPane().add(jlblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        btngrpSexe.add(jrbtnMasculin);
        jrbtnMasculin.setText("M");
        jrbtnMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnMasculinActionPerformed(evt);
            }
        });
        getContentPane().add(jrbtnMasculin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        btngrpSexe.add(jrbtnFeminin);
        jrbtnFeminin.setText("F");
        getContentPane().add(jrbtnFeminin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        toolBar.setRollover(true);
        toolBar.setName("Rendez-vous"); // NOI18N

        tbtnRDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtnRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/calendrier (1).jpg"))); // NOI18N
        tbtnRDV.setText("Gestion des Rendez-vous");
        tbtnRDV.setFocusable(false);
        tbtnRDV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnRDV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRDVActionPerformed(evt);
            }
        });
        toolBar.add(tbtnRDV);

        tbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtnPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/patient.png"))); // NOI18N
        tbtnPatient.setText("Gestion des Patients");
        tbtnPatient.setFocusable(false);
        tbtnPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPatientActionPerformed(evt);
            }
        });
        toolBar.add(tbtnPatient);

        getContentPane().add(toolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomActionPerformed

    private void jtfDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDateActionPerformed

    private void jtfTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelephoneActionPerformed

    private void jbtAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAjouterActionPerformed
        // TODO add your handling code here:
        String id=jtfId.getText();
            String nom=jtfNom.getText();
            String prenom=jtfPrenom.getText();
            String age=jtfAge.getText();
            String sexe;
            String date=jtfDate.getText();
            String cin=jtfCIN.getText();
            String tel=jtfTelephone.getText();
            String adresse=jtfAdresse.getText();
            if(jrbtnFeminin.isSelected())
                sexe="F";
            else
                sexe="M";
    
        if(id.isEmpty()||prenom.isEmpty()||age.isEmpty()||date.isEmpty()||cin.isEmpty()||tel.isEmpty()||adresse.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Veuillez saisir tous les details");
            jtfId.setText("");
            jtfNom.getText();
            jtfPrenom.getText();
            jtfAge.getText();
            jtfDate.getText();
            jtfCIN.getText();
            jtfTelephone.getText();
            jtfAdresse.getText();
        }
        else
        {
            try
            {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt=(Statement)conn.createStatement();   
                String query="Insert Into patient values ('"+id+"','"+nom+"','"+prenom+"','"+age+"','"+sexe+"','"+date+"', '"+cin+"', '"+tel+"', '"+adresse+"');";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Patient ajouté");                            

            }
            catch( SQLException e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtAjouterActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jrbtnMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnMasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnMasculinActionPerformed

    private void jbtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSupprimerActionPerformed
        // TODO add your handling code here:
        String supprimer;
        String Id="";
        supprimer=jtfId.getText();
        if(supprimer.isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez saisir l id du patient à supprimer");
           jtfId.setText("saisisser l id ici");
        }
        else{
            try
            {
        	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
        	Statement stmt=(Statement) conn.createStatement();
        	String query="select idP from patient where idP='"+supprimer+"';";
                ResultSet rs=stmt.executeQuery(query);            
                while(rs.next())
                {
                    Id=rs.getString("idP");
                }
                
                if(supprimer.equals(Id))
                {
                    try
                    {
                    	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                    	Statement stmt1=(Statement)con.createStatement();   
			String query1="delete from patient where idP='"+supprimer+"';";
		        stmt1.executeUpdate(query1);
                        JOptionPane.showMessageDialog(this,"patient supprimé");	                                
		    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(this,e.getMessage());
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Ce patient n existe pas dans la base");
                }
            }
            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtnSupprimerActionPerformed

    private void jbtnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualiserActionPerformed
        afficher();
    }//GEN-LAST:event_jbtnActualiserActionPerformed

    private void jtabPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabPatientMouseClicked
        // TODO add your handling code here:
        try{
            int i=jtabPatient.getSelectedRow();
            deplace(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erreur de deplacement");
        }
    }//GEN-LAST:event_jtabPatientMouseClicked

    private void jbtnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRechercherActionPerformed
       try{
           model.setRowCount(0);
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM patient WHERE idP='"+jtfId.getText()+"';";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String id = rs.getString("idP");
                String nom = rs.getString("nom");
                String prenom=rs.getString("prenom");
                String age=rs.getString("age");
                String sexe=rs.getString("sexe");
                String date=rs.getString("dateAdmission");
                String CIN=rs.getString("CIN");
                String telephone=rs.getString("telephone");
                String adresse=rs.getString("adresse");

                model.addRow (new Object[] {id,nom,prenom, age, sexe, date, CIN, telephone, adresse});
            }
            jtabPatient.setModel(model);
            if(model.getRowCount()==0)
                JOptionPane.showMessageDialog(null, "Il n'y a aucun etudiant de ce nom");
            else{
                int i=0;
                deplace(i);
            }
           
       }
       catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jbtnRechercherActionPerformed

    private void jbtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifierActionPerformed
       if(jtfId.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Veuiller selectionner dans le tableau la ligne du patient à modifier");
       }
       else{
           try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt = (Statement) conn.createStatement();
                String query="UPDATE Patient SET Nom='"+jtfNom.getText()+"',Prenom='"+jtfPrenom.getText()+"',Age='"+jtfAge.getText()+"', dateAdmission='"+jtfDate.getText()+"', Telephone='"+jtfTelephone.getText()+"', CIN='"+jtfCIN.getText()+"', Adresse='"+jtfAdresse.getText()+"' WHERE idP= "+jtfId.getText()+";";
                stmt.executeUpdate(query);
                afficher();          
            } 
        } catch (HeadlessException | SQLException e){JOptionPane.showMessageDialog(null,"erreur de modification!"+e.getMessage());
        }
       }
        
    }//GEN-LAST:event_jbtnModifierActionPerformed

    private void tbtnRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRDVActionPerformed
        new GestionRDV().setVisible(true);
    }//GEN-LAST:event_tbtnRDVActionPerformed

    private void tbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPatientActionPerformed
        new GestionDePatients().setVisible(true);
    }//GEN-LAST:event_tbtnPatientActionPerformed

    private void jbtnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimerActionPerformed
        // TODO add your handling code here:
        DossierMedical fiche=new DossierMedical();
        fiche.setNumDossier(jtfId.getText());
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM patient,Consultation WHERE patient.idP=Consultation.idP and patient.IdP='"+jtfId.getText()+"';";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                fiche.setNom(rs.getString("nom"));
                fiche.setPrenom(rs.getString("prenom"));
                fiche.setAge(rs.getString("Age"));
                fiche.setSexe(rs.getString("Sexe"));
                fiche.setDateVisite(rs.getString("dateAdmission"));
                fiche.setCIN(rs.getString("CIN"));
                fiche.setTel(rs.getString("telephone"));
                fiche.setAdresse(rs.getString("adresse"));
                
                fiche.setNumConsultation(rs.getString("numConsultation"));
                fiche.setdateConsultation(rs.getString("date_consultation"));
                fiche.setTemperature(rs.getString("Temperature"));
                fiche.setPoids(rs.getString("Poids"));
                fiche.setTension(rs.getString("Tension"));
                fiche.setTaille(rs.getString("Taille"));
                fiche.setMotifs(rs.getString("MotifsConsultation"));
                fiche.setSignes(rs.getString("signesGeneraux"));
                fiche.setAntecedents(rs.getString("Antecedents"));
                fiche.setExamen(rs.getString("Examen"));
                fiche.setDiagnostique(rs.getString("Diagnostique"));
                fiche.setOrdonnance(rs.getString("Ordonnance"));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    fiche.setVisible(true);
    }//GEN-LAST:event_jbtnImprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDePatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpSexe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAjouter;
    private javax.swing.JButton jbtnActualiser;
    private javax.swing.JButton jbtnImprimer;
    private javax.swing.JButton jbtnModifier;
    private javax.swing.JButton jbtnRechercher;
    private javax.swing.JButton jbtnSupprimer;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblId;
    private javax.swing.JLabel jlblNom;
    private javax.swing.JLabel jlblPrenom;
    private javax.swing.JLabel jlblSexe;
    private javax.swing.JRadioButton jrbtnFeminin;
    private javax.swing.JRadioButton jrbtnMasculin;
    private javax.swing.JTable jtabPatient;
    private javax.swing.JTextField jtfAdresse;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfCIN;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfPrenom;
    private javax.swing.JTextField jtfTelephone;
    private javax.swing.JButton tbtnPatient;
    private javax.swing.JButton tbtnRDV;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
