/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

/**
 *
 * @author hp
 */
public class GestionMedecins extends javax.swing.JFrame {

    /**
     * Creates new form GestionMedecins
     */
    public GestionMedecins() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNum = new javax.swing.JLabel();
        jlblNom = new javax.swing.JLabel();
        jlblPrenom = new javax.swing.JLabel();
        jlblSpecialite = new javax.swing.JLabel();
        jlblTel = new javax.swing.JLabel();
        jlblAdresse = new javax.swing.JLabel();
        jtfNum = new javax.swing.JTextField();
        jtfNom = new javax.swing.JTextField();
        jtfPrenom = new javax.swing.JTextField();
        jtfSpecialite = new javax.swing.JTextField();
        jtfTel = new javax.swing.JTextField();
        jtfAdresse = new javax.swing.JTextField();
        jtfRechercher = new javax.swing.JTextField();
        jbtnRechercher = new javax.swing.JButton();
        jbtnAjouter = new javax.swing.JButton();
        jbtnModifier = new javax.swing.JButton();
        jbtnSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlblMedecins = new javax.swing.JLabel();
        jlblFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNum.setText("Numéro");
        getContentPane().add(jlblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlblNom.setText("Nom");
        getContentPane().add(jlblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jlblPrenom.setText("Prenom");
        getContentPane().add(jlblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, -1));

        jlblSpecialite.setText("Spécialité");
        getContentPane().add(jlblSpecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jlblTel.setText("Téléphone");
        getContentPane().add(jlblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jlblAdresse.setText("Adresse");
        getContentPane().add(jlblAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));
        getContentPane().add(jtfNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 159, -1));
        getContentPane().add(jtfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 159, -1));
        getContentPane().add(jtfPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 159, -1));
        getContentPane().add(jtfSpecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 159, -1));
        getContentPane().add(jtfTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 159, -1));
        getContentPane().add(jtfAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 159, -1));
        getContentPane().add(jtfRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 120, 30));

        jbtnRechercher.setText("Rechercher");
        getContentPane().add(jbtnRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 100, 40));

        jbtnAjouter.setText("Ajouter");
        getContentPane().add(jbtnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        jbtnModifier.setText("Modifier");
        getContentPane().add(jbtnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jbtnSupprimer.setText("Supprimer");
        getContentPane().add(jbtnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nom", "Prenom", "Telephone", "Specialité", "Adresse"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 520, 292));

        jlblMedecins.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jlblMedecins.setForeground(new java.awt.Color(0, 51, 255));
        jlblMedecins.setText("Gestion des Médécins");
        getContentPane().add(jlblMedecins, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 370, 50));

        jlblFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/medecins.jpg"))); // NOI18N
        jlblFond.setText("jLabel2");
        getContentPane().add(jlblFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMedecins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMedecins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMedecins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMedecins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMedecins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAjouter;
    private javax.swing.JButton jbtnModifier;
    private javax.swing.JButton jbtnRechercher;
    private javax.swing.JButton jbtnSupprimer;
    private javax.swing.JLabel jlblAdresse;
    private javax.swing.JLabel jlblFond;
    private javax.swing.JLabel jlblMedecins;
    private javax.swing.JLabel jlblNom;
    private javax.swing.JLabel jlblNum;
    private javax.swing.JLabel jlblPrenom;
    private javax.swing.JLabel jlblSpecialite;
    private javax.swing.JLabel jlblTel;
    private javax.swing.JTextField jtfAdresse;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfNum;
    private javax.swing.JTextField jtfPrenom;
    private javax.swing.JTextField jtfRechercher;
    private javax.swing.JTextField jtfSpecialite;
    private javax.swing.JTextField jtfTel;
    // End of variables declaration//GEN-END:variables
}
