/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class GestionPersonnels extends javax.swing.JFrame {

    /**
     * Creates new form GestionPersonnels
     */
    DefaultTableModel model = new DefaultTableModel();
    public GestionPersonnels() {
        initComponents();
        model.addColumn("idM");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("Fonction");
        model.addColumn("telephone");
        model.addColumn("specialité");
        model.addColumn("adresse");
        model.addColumn("Mot de passe");
        afficher();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void deplace(int i){
        try{
            jtfId.setText(model.getValueAt(i, 0).toString());
            jtfNom.setText(model.getValueAt(i, 1).toString());
            jtfPrenom.setText(model.getValueAt(i, 2).toString());
            jcomboFonction.setSelectedItem(model.getValueAt(i, 3).toString());
            jtfTelephone.setText(model.getValueAt(i, 4).toString());
            jtfSpecialite.setText(model.getValueAt(i, 5).toString());
            jtfAdresse.setText(model.getValueAt(i, 6).toString());
            jtfMdp.setText(model.getValueAt(i, 7).toString());
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement");
        }
    }
    
    private void afficher(){
    try {
        model.setRowCount(0);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM personnels;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String id = rs.getString("idM");
                String nom = rs.getString("nom");
                String prenom=rs.getString("prenom");
                String fonction=rs.getString("fonction");
                String telephone=rs.getString("telephone");
                String specialite=rs.getString("specialite");
                String adresse=rs.getString("adresse");
                String mdp=rs.getString("mdp");

                model.addRow (new Object[] {id,nom,prenom,fonction, telephone, specialite, adresse,mdp});
            }
            jtabPersonnels.setModel(model);

    }
    catch (SQLException e)
        {
            
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblId = new javax.swing.JLabel();
        jlblNom = new javax.swing.JLabel();
        jlblPrenom = new javax.swing.JLabel();
        jlblSpecialite = new javax.swing.JLabel();
        jlblTel = new javax.swing.JLabel();
        jlblAdresse = new javax.swing.JLabel();
        jlblFonction = new javax.swing.JLabel();
        jlblMdp = new javax.swing.JLabel();
        jtfNom = new javax.swing.JTextField();
        jtfSpecialite = new javax.swing.JTextField();
        jtfTelephone = new javax.swing.JTextField();
        jtfAdresse = new javax.swing.JTextField();
        jtfId = new javax.swing.JTextField();
        jtfPrenom = new javax.swing.JTextField();
        jtfMdp = new javax.swing.JTextField();
        jcomboFonction = new javax.swing.JComboBox<>();
        jbtnRechercher = new javax.swing.JButton();
        jbtnAjouter = new javax.swing.JButton();
        jbtnModifier = new javax.swing.JButton();
        jbtnSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabPersonnels = new javax.swing.JTable();
        jlblMedecins = new javax.swing.JLabel();
        jbtnActualiser = new javax.swing.JButton();
        toolBar = new javax.swing.JToolBar();
        tbtnMedecins = new javax.swing.JButton();
        tbtnChambres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion du Parsonnel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblId.setText("ID");
        getContentPane().add(jlblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jlblNom.setText("Nom");
        getContentPane().add(jlblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jlblPrenom.setText("Prenom");
        getContentPane().add(jlblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jlblSpecialite.setText("Spécialité");
        getContentPane().add(jlblSpecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jlblTel.setText("Téléphone");
        getContentPane().add(jlblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jlblAdresse.setText("Adresse");
        getContentPane().add(jlblAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jlblFonction.setText("Fonction");
        getContentPane().add(jlblFonction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jlblMdp.setText("Mot de Passe");
        getContentPane().add(jlblMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(jtfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 159, -1));
        getContentPane().add(jtfSpecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 159, -1));
        getContentPane().add(jtfTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 159, -1));
        getContentPane().add(jtfAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 159, -1));
        getContentPane().add(jtfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 140, 40));
        getContentPane().add(jtfPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));
        getContentPane().add(jtfMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, -1));

        jcomboFonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medecin", "Infirmière", "Secretaire" }));
        getContentPane().add(jcomboFonction, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, -1));

        jbtnRechercher.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/rechercher.png"))); // NOI18N
        jbtnRechercher.setText("Rechercher");
        jbtnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, 40));

        jbtnAjouter.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/ajoutP.png"))); // NOI18N
        jbtnAjouter.setText("Ajouter");
        jbtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 140, -1));

        jbtnModifier.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/modier.jpg"))); // NOI18N
        jbtnModifier.setText("Modifier");
        jbtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 140, -1));

        jbtnSupprimer.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/supprimer.png"))); // NOI18N
        jbtnSupprimer.setText("Supprimer");
        jbtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 140, -1));

        jtabPersonnels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nom", "Prenom", "Fonction", "Telephone", "Specialité", "Adresse", "Mot de Passe"
            }
        ));
        jtabPersonnels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabPersonnelsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabPersonnels);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 690, 140));

        jlblMedecins.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jlblMedecins.setForeground(new java.awt.Color(0, 51, 255));
        jlblMedecins.setText("Gestion du Personnel");
        getContentPane().add(jlblMedecins, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 370, 50));

        jbtnActualiser.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/actualiser.png"))); // NOI18N
        jbtnActualiser.setText("Actualiser");
        jbtnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualiserActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 140, -1));

        toolBar.setRollover(true);
        toolBar.setName("Rendez-vous"); // NOI18N

        tbtnMedecins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtnMedecins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/Medecin.png"))); // NOI18N
        tbtnMedecins.setText("Gestion des Médécins");
        tbtnMedecins.setFocusable(false);
        tbtnMedecins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnMedecins.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnMedecins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnMedecinsActionPerformed(evt);
            }
        });
        toolBar.add(tbtnMedecins);

        tbtnChambres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtnChambres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/chambre.jpg"))); // NOI18N
        tbtnChambres.setText("Gestion des Chambres");
        tbtnChambres.setFocusable(false);
        tbtnChambres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnChambres.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnChambres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnChambresActionPerformed(evt);
            }
        });
        toolBar.add(tbtnChambres);

        getContentPane().add(toolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnMedecinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMedecinsActionPerformed
        new GestionPersonnels().setVisible(true);
    }//GEN-LAST:event_tbtnMedecinsActionPerformed

    private void tbtnChambresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnChambresActionPerformed
        new GestionChambres().setVisible(true);
    }//GEN-LAST:event_tbtnChambresActionPerformed

    private void jtabPersonnelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabPersonnelsMouseClicked
        try{
            int i=jtabPersonnels.getSelectedRow();
            deplace(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erreur de deplacement");
        }
    }//GEN-LAST:event_jtabPersonnelsMouseClicked

    private void jbtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjouterActionPerformed
        String id=jtfId.getText();
            String nom=jtfNom.getText();
            String prenom=jtfPrenom.getText();
            String fonction=jcomboFonction.getSelectedItem().toString();
            String mdp=jtfMdp.getText();
            String tel=jtfTelephone.getText();
            String specialite=jtfSpecialite.getText();
            String adresse=jtfAdresse.getText();
            
        if(id.isEmpty()||prenom.isEmpty()|| tel.isEmpty()|| specialite.isEmpty()||adresse.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Veuillez remplir tous les champs");
            
        }
        else
        {
            try
            {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt=(Statement)conn.createStatement();   
                String query="Insert Into personnels values ('"+id+"','"+nom+"','"+prenom+"', '"+fonction+"', "+tel+"', '"+specialite+"', '"+adresse+"','"+mdp+"');";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Nouveau docteur ajouté");                            

            }
            catch( SQLException e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtnAjouterActionPerformed

    private void jbtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifierActionPerformed
        if(jtfId.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Veuiller selectionner dans le tableau la ligne de l'employe à modifier");
       }
       else{
           try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt = (Statement) conn.createStatement();
                String query="UPDATE personnels SET Nom='"+jtfNom.getText()+"',Prenom='"+jtfPrenom.getText()+"', fonction='"+jcomboFonction.getSelectedItem().toString()+"', Telephone='"+jtfTelephone.getText()+"', specialite='"+jtfSpecialite.getText()+"', Adresse='"+jtfAdresse.getText()+"',mdp='"+jtfMdp.getText()+"' WHERE idM= "+jtfId.getText()+";";
                stmt.executeUpdate(query);
                afficher();          
            } 
        } catch (HeadlessException | SQLException e){JOptionPane.showMessageDialog(null,"erreur de modification!"+e.getMessage());
        }
       }
    }//GEN-LAST:event_jbtnModifierActionPerformed

    private void jbtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSupprimerActionPerformed
        String supprimer;
        String Id="";
        supprimer=jtfId.getText();
        if(supprimer.isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez saisir l id du patient à supprimer");
           jtfId.setText("saisisser l id ici");
        }
        else{
            try
            {
        	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
        	Statement stmt=(Statement) conn.createStatement();
        	String query="select idM from personnels where idM='"+supprimer+"';";
                ResultSet rs=stmt.executeQuery(query);            
                while(rs.next())
                {
                    Id=rs.getString("idM");
                }
                
                if(supprimer.equals(Id))
                {
                    try
                    {
                    	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                    	Statement stmt1=(Statement)con.createStatement();   
			String query1="delete from personnels where idM='"+supprimer+"';";
		        stmt1.executeUpdate(query1);
                        JOptionPane.showMessageDialog(this,"employé supprimé");	                                
		    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(this,e.getMessage());
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cet employé n existe pas dans la base");
                }
            }
            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtnSupprimerActionPerformed

    private void jbtnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualiserActionPerformed
        afficher();
    }//GEN-LAST:event_jbtnActualiserActionPerformed

    private void jbtnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRechercherActionPerformed
        try{
           model.setRowCount(0);
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM personnels WHERE idM='"+jtfId.getText()+"';";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String id = rs.getString("idM");
                String nom = rs.getString("nom");
                String prenom=rs.getString("prenom");
                String fonction=rs.getString("fonction");
                String telephone=rs.getString("telephone");
                String specialite=rs.getString("specialite");
                String adresse=rs.getString("adresse");
                String mdp=rs.getString("mdp");

                model.addRow (new Object[] {id,nom,prenom,fonction, telephone, specialite, adresse,mdp});
            }
            jtabPersonnels.setModel(model);
            if(model.getRowCount()==0)
                JOptionPane.showMessageDialog(null, "Il n'y a aucun personnel de ce nom");
            else{
                int i=0;
                deplace(i);
            }
           
       }
       catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jbtnRechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersonnels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPersonnels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualiser;
    private javax.swing.JButton jbtnAjouter;
    private javax.swing.JButton jbtnModifier;
    private javax.swing.JButton jbtnRechercher;
    private javax.swing.JButton jbtnSupprimer;
    private javax.swing.JComboBox<String> jcomboFonction;
    private javax.swing.JLabel jlblAdresse;
    private javax.swing.JLabel jlblFonction;
    private javax.swing.JLabel jlblId;
    private javax.swing.JLabel jlblMdp;
    private javax.swing.JLabel jlblMedecins;
    private javax.swing.JLabel jlblNom;
    private javax.swing.JLabel jlblPrenom;
    private javax.swing.JLabel jlblSpecialite;
    private javax.swing.JLabel jlblTel;
    private javax.swing.JTable jtabPersonnels;
    private javax.swing.JTextField jtfAdresse;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfMdp;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfPrenom;
    private javax.swing.JTextField jtfSpecialite;
    private javax.swing.JTextField jtfTelephone;
    private javax.swing.JButton tbtnChambres;
    private javax.swing.JButton tbtnMedecins;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
