/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

/**
 *
 * @author hp
 */
public class Secretaire extends javax.swing.JFrame {

    /**
     * Creates new form Secretaire
     */
    public Secretaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblClinique = new javax.swing.JLabel();
        jlblSecretaire = new javax.swing.JLabel();
        jbtnPatients = new javax.swing.JButton();
        jbtnRdv = new javax.swing.JButton();
        jbtnMedecins = new javax.swing.JButton();
        jbtnCompta = new javax.swing.JButton();
        jbtnChambres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlblClinique.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jlblClinique.setForeground(new java.awt.Color(51, 51, 255));
        jlblClinique.setText("Cinique Ashila");

        jlblSecretaire.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlblSecretaire.setText("Espace Secrétaire");

        jbtnPatients.setBackground(new java.awt.Color(0, 204, 255));
        jbtnPatients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnPatients.setText("Gestion des Patients");
        jbtnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientsActionPerformed(evt);
            }
        });

        jbtnRdv.setBackground(new java.awt.Color(0, 204, 255));
        jbtnRdv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRdv.setText("Gestion des Rendez-Vous!");
        jbtnRdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRdvActionPerformed(evt);
            }
        });

        jbtnMedecins.setBackground(new java.awt.Color(0, 204, 255));
        jbtnMedecins.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnMedecins.setText("Gestion des Médécins");
        jbtnMedecins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMedecinsActionPerformed(evt);
            }
        });

        jbtnCompta.setBackground(new java.awt.Color(0, 204, 255));
        jbtnCompta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCompta.setText("Gestion de la comptabilité");
        jbtnCompta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComptaActionPerformed(evt);
            }
        });

        jbtnChambres.setBackground(new java.awt.Color(0, 204, 255));
        jbtnChambres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnChambres.setText("Gestion des chambres");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/secretaire.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jbtnRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtnMedecins, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtnPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jlblSecretaire, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jlblClinique, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jbtnChambres, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jbtnCompta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jbtnRdv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jbtnMedecins, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jbtnPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jlblSecretaire))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlblClinique, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jbtnChambres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jbtnCompta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientsActionPerformed
        // TODO add your handling code here:
        new GestionPatients().setVisible(true);
    }//GEN-LAST:event_jbtnPatientsActionPerformed

    private void jbtnRdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRdvActionPerformed
        // TODO add your handling code here:
        new GestionRDV().setVisible(true);
    }//GEN-LAST:event_jbtnRdvActionPerformed

    private void jbtnMedecinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMedecinsActionPerformed
        // TODO add your handling code here:
        new GestionMedecins().setVisible(true);
    }//GEN-LAST:event_jbtnMedecinsActionPerformed

    private void jbtnComptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComptaActionPerformed
        // TODO add your handling code here:
        new Facture().setVisible(true);
    }//GEN-LAST:event_jbtnComptaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secretaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnChambres;
    private javax.swing.JButton jbtnCompta;
    private javax.swing.JButton jbtnMedecins;
    private javax.swing.JButton jbtnPatients;
    private javax.swing.JButton jbtnRdv;
    private javax.swing.JLabel jlblClinique;
    private javax.swing.JLabel jlblSecretaire;
    // End of variables declaration//GEN-END:variables
}
