/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.de.clinique;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Service extends javax.swing.JFrame {

    /**
     * Creates new form Service
     */
    DefaultTableModel model = new DefaultTableModel();
    public Service() {
        initComponents();
        model.addColumn("Id Service");
        model.addColumn("Nom Service");
        model.addColumn("Prix Service");
         
        afficher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void deplace(int i){
        try{
            jtfId.setText(model.getValueAt(i, 0).toString());
            jtfNom.setText(model.getValueAt(i, 1).toString());
            jtfPrix.setText(model.getValueAt(i, 2).toString());
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement");
        }
    }
    
    private void afficher(){
    try {
        model.setRowCount(0);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
            Statement stmt = (Statement) conn.createStatement();
            String query="SELECT * FROM service;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String id = rs.getString("idService");
                String nom = rs.getString("nomService");
                String prix=rs.getString("prixService");
               
                model.addRow (new Object[] {id,nom,prix});
            }
            jtabService.setModel(model);

    }
    catch (SQLException e)
        {
            
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabService = new javax.swing.JTable();
        jbtnAjouter = new javax.swing.JButton();
        jbtnModifier = new javax.swing.JButton();
        jbtnSupprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfNom = new javax.swing.JTextField();
        jtfPrix = new javax.swing.JTextField();
        toolBar = new javax.swing.JToolBar();
        tbtnFacture = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Service", "Nom Service", "Prix Service"
            }
        ));
        jtabService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabService);

        jbtnAjouter.setText("ajouter");
        jbtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjouterActionPerformed(evt);
            }
        });

        jbtnModifier.setText("Modifier");
        jbtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifierActionPerformed(evt);
            }
        });

        jbtnSupprimer.setText("Supprimer");
        jbtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSupprimerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Mise à jour des Services");

        jLabel2.setText("Id");

        jLabel3.setText("Nom Service");

        jLabel4.setText("Prix");

        toolBar.setRollover(true);
        toolBar.setName("Rendez-vous"); // NOI18N

        tbtnFacture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtnFacture.setForeground(new java.awt.Color(51, 51, 0));
        tbtnFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/de/clinique/icon/facture.png"))); // NOI18N
        tbtnFacture.setText("Paiement");
        tbtnFacture.setFocusable(false);
        tbtnFacture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnFacture.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnFactureActionPerformed(evt);
            }
        });
        toolBar.add(tbtnFacture);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Service");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        toolBar.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jbtnAjouter)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jbtnModifier)
                                .addGap(52, 52, 52)
                                .addComponent(jbtnSupprimer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfId)
                                    .addComponent(jtfNom)
                                    .addComponent(jtfPrix, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAjouter)
                    .addComponent(jbtnModifier)
                    .addComponent(jbtnSupprimer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjouterActionPerformed
        String id=jtfId.getText();
            String nom=jtfNom.getText();
            String prix=jtfPrix.getText();
            
        if(id.isEmpty()||nom.isEmpty()||prix.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Veuillez saisir tous les details");
            jtfId.setText("");
            jtfNom.getText();
            jtfPrix.getText();
            
        }
        else
        {
            try
            {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt=(Statement)conn.createStatement();   
                String query="Insert Into service values ('"+id+"','"+nom+"','"+prix+"');";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Nouveau service ajouté");                            

            }
            catch( SQLException e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtnAjouterActionPerformed

    private void jbtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifierActionPerformed
        if(jtfId.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Veuiller selectionner dans le tableau la ligne du patient à modifier");
       }
       else{
           try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                Statement stmt = (Statement) conn.createStatement();
                String query="UPDATE service SET NomService='"+jtfNom.getText()+"',PrixService='"+jtfPrix.getText()+"' WHERE idService= "+jtfId.getText()+";";
                stmt.executeUpdate(query);
                afficher();          
            } 
        } catch (HeadlessException | SQLException e){JOptionPane.showMessageDialog(null,"erreur de modification!"+e.getMessage());
        }
       }
    }//GEN-LAST:event_jbtnModifierActionPerformed

    private void jbtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSupprimerActionPerformed
        String supprimer;
        String Id="";
        supprimer=jtfId.getText();
        if(supprimer.isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez saisir l id du patient à supprimer");
           jtfId.setText("saisisser l id ici");
        }
        else{
            try
            {
        	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
        	Statement stmt=(Statement) conn.createStatement();
        	String query="select idService from service where idService='"+supprimer+"';";
                ResultSet rs=stmt.executeQuery(query);            
                while(rs.next())
                {
                    Id=rs.getString("idService");
                }
                
                if(supprimer.equals(Id))
                {
                    try
                    {
                    	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/pi?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC","root", "");
                    	Statement stmt1=(Statement)con.createStatement();   
			String query1="delete from service where idService='"+supprimer+"';";
		        stmt1.executeUpdate(query1);
                        JOptionPane.showMessageDialog(this,"Service supprimé");	                                
		    }
                    catch(SQLException e)
                    {
                        JOptionPane.showMessageDialog(this,e.getMessage());
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Ce service n existe pas dans la base");
                }
            }
            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        afficher();
    }//GEN-LAST:event_jbtnSupprimerActionPerformed

    private void jtabServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabServiceMouseClicked
        try{
            int i=jtabService.getSelectedRow();
            deplace(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erreur de deplacement");
        }
    }//GEN-LAST:event_jtabServiceMouseClicked

    private void tbtnFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnFactureActionPerformed
        new Facture().setVisible(true);
    }//GEN-LAST:event_tbtnFactureActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Service().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAjouter;
    private javax.swing.JButton jbtnModifier;
    private javax.swing.JButton jbtnSupprimer;
    private javax.swing.JTable jtabService;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNom;
    private javax.swing.JTextField jtfPrix;
    private javax.swing.JButton tbtnFacture;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
